#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerowanieNotDoWyslania.ErpxlAddon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CDNXL_PNIPH_KSI_TEST")]
	public partial class SQLDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SQLDataDataContext() : 
				base(global::GenerowanieNotDoWyslania.ErpxlAddon.Properties.Settings.Default.CDNXL_PNIPH_KSI_TESTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetCrmKampNag")]
		public ISingleResult<T2S_GetCrmKampNagResult> T2S_GetCrmKampNag()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<T2S_GetCrmKampNagResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetKampNagEtapy")]
		public ISingleResult<T2S_GetKampNagEtapyResult> T2S_GetKampNagEtapy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KampNagNumer", DbType="Int")] System.Nullable<int> kampNagNumer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kampNagNumer);
			return ((ISingleResult<T2S_GetKampNagEtapyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetGenNotLastNumer")]
		public ISingleResult<T2S_GetGenNotLastNumerResult> T2S_GetGenNotLastNumer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date);
			return ((ISingleResult<T2S_GetGenNotLastNumerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_SaveGenNotLastNumer")]
		public int T2S_SaveGenNotLastNumer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numer", DbType="Int")] System.Nullable<int> numer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, numer);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_AddBinaryData")]
		public ISingleResult<T2S_AddBinaryDataResult> T2S_AddBinaryData([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kod", DbType="VarChar(39)")] string kod, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nazwa", DbType="VarChar(99)")] string nazwa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rozszerzenie", DbType="VarChar(31)")] string rozszerzenie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Plik", DbType="Image")] System.Data.Linq.Binary plik, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK", DbType="Int")] System.Nullable<int> pK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GidTyp", DbType="Int")] System.Nullable<int> gidTyp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GidNumer", DbType="Int")] System.Nullable<int> gidNumer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kod, nazwa, rozszerzenie, plik, pK, gidTyp, gidNumer);
			return ((ISingleResult<T2S_AddBinaryDataResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetGenNotEtapInfo")]
		public ISingleResult<T2S_GetGenNotEtapInfoResult> T2S_GetGenNotEtapInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="KampNumer", DbType="Int")] System.Nullable<int> kampNumer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KampLp", DbType="Int")] System.Nullable<int> kampLp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OpeNumer", DbType="Int")] System.Nullable<int> opeNumer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kampNumer, kampLp, opeNumer);
			return ((ISingleResult<T2S_GetGenNotEtapInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetReportsGenNot")]
		public ISingleResult<T2S_GetReportsGenNotResult> T2S_GetReportsGenNot()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<T2S_GetReportsGenNotResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GetEmailNotaStatut")]
		public ISingleResult<T2S_GetEmailNotaStatutResult> T2S_GetEmailNotaStatut([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kntnumer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> openumer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kntnumer, openumer);
			return ((ISingleResult<T2S_GetEmailNotaStatutResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_UpdateAtrybut")]
		public int T2S_UpdateAtrybut([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> typ, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sublp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string klasa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(512)")] string wartosc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> autoCreateGidTyp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), typ, numer, lp, sublp, klasa, wartosc, login, autoCreateGidTyp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_Procedure_CounterGenerateNots")]
		public ISingleResult<T2S_Procedure_CounterGenerateNotsResult> T2S_Procedure_CounterGenerateNots([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numer_noty, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> opcja)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numer_noty, opcja);
			return ((ISingleResult<T2S_Procedure_CounterGenerateNotsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENota")]
		public ISingleResult<T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENotaResult> T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENota([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numer", DbType="Int")] System.Nullable<int> numer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lp", DbType="Int")] System.Nullable<int> lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numer, lp);
			return ((ISingleResult<T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENotaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GenNagEtapKnt")]
		public ISingleResult<T2S_GenNagEtapKntResult> T2S_GenNagEtapKnt([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numer", DbType="Int")] System.Nullable<int> numer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lp", DbType="Int")] System.Nullable<int> lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numer, lp);
			return ((ISingleResult<T2S_GenNagEtapKntResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GenNagEtapKntTAK")]
		public ISingleResult<T2S_GenNagEtapKntTAKResult> T2S_GenNagEtapKntTAK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numer", DbType="Int")] System.Nullable<int> numer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lp", DbType="Int")] System.Nullable<int> lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numer, lp);
			return ((ISingleResult<T2S_GenNagEtapKntTAKResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_GenNagEtapKntNIE")]
		public ISingleResult<T2S_GenNagEtapKntNIEResult> T2S_GenNagEtapKntNIE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numer", DbType="Int")] System.Nullable<int> numer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lp", DbType="Int")] System.Nullable<int> lp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numer, lp);
			return ((ISingleResult<T2S_GenNagEtapKntNIEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_Procedure_PobierzAdresMailowy")]
		public ISingleResult<T2S_Procedure_PobierzAdresMailowyResult> T2S_Procedure_PobierzAdresMailowy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPlatnosci", DbType="BigInt")] System.Nullable<long> idPlatnosci)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPlatnosci);
			return ((ISingleResult<T2S_Procedure_PobierzAdresMailowyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="CDN.T2S_Procedure_PobierzAdresMailowyOdbiorcy")]
		public ISingleResult<T2S_Procedure_PobierzAdresMailowyOdbiorcyResult> T2S_Procedure_PobierzAdresMailowyOdbiorcy([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEK_ID", DbType="BigInt")] System.Nullable<long> CEK_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), CEK_ID); 
			return ((ISingleResult<T2S_Procedure_PobierzAdresMailowyOdbiorcyResult>)(result.ReturnValue));
		}
	}
	
	public partial class T2S_GetCrmKampNagResult
	{
		
		private string _Kod;
		
		private int _Numer;
		
		public T2S_GetCrmKampNagResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="VarChar(30)")]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this._Kod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numer", DbType="Int NOT NULL")]
		public int Numer
		{
			get
			{
				return this._Numer;
			}
			set
			{
				if ((this._Numer != value))
				{
					this._Numer = value;
				}
			}
		}
	}
	
	public partial class T2S_GetKampNagEtapyResult
	{
		
		private string _Kod;
		
		private short _Lp;
		
		public T2S_GetKampNagEtapyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="VarChar(40)")]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this._Kod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lp", DbType="SmallInt NOT NULL")]
		public short Lp
		{
			get
			{
				return this._Lp;
			}
			set
			{
				if ((this._Lp != value))
				{
					this._Lp = value;
				}
			}
		}
	}
	
	public partial class T2S_GetGenNotLastNumerResult
	{
		
		private System.Nullable<int> _Result;
		
		public T2S_GetGenNotLastNumerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class T2S_AddBinaryDataResult
	{
		
		private System.Nullable<int> _Column1;
		
		public T2S_AddBinaryDataResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class T2S_GetGenNotEtapInfoResult
	{
		
		private string _WalneZgromadzenieRok;
		
		private string _SkładkaRok;
		
		private string _SkładkaWysokość;

        private string _SkładkaWysokośćEURO;

        private string _SkładkaTermin;
		
		private string _SkładkaKoszty;
		
		private string _NumerRachunku;

        private string _NumerRachunkuDE;

        private string _NazwaBanku;

        private string _NazwaBankuDE;

        private string _InfoDodatkowe;
		
		private string _PodstawaPrawna;
		
		private string _Podpis;

        private string _PodpisDE;

        private string _Folder;
		
		private string _Typ;
		
		private string _DataNota;
		
		private string _SchematNumer;
		
		private string _InfoDodatkoweDE;
		
		private string _PodstawaPrawnaDE;
		
		private string _IloscDni;
		
		private string _NazwaNoty;
		
		private int _CkeNumer;
		
		private System.Nullable<short> _CkeTyp;
		
		private short _CkeLp;
		
		private string _OpeIdent;
		
		public T2S_GetGenNotEtapInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WalneZgromadzenieRok", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string WalneZgromadzenieRok
		{
			get
			{
				return this._WalneZgromadzenieRok;
			}
			set
			{
				if ((this._WalneZgromadzenieRok != value))
				{
					this._WalneZgromadzenieRok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkładkaRok", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SkładkaRok
		{
			get
			{
				return this._SkładkaRok;
			}
			set
			{
				if ((this._SkładkaRok != value))
				{
					this._SkładkaRok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkładkaWysokość", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SkładkaWysokość
		{
			get
			{
				return this._SkładkaWysokość;
			}
			set
			{
				if ((this._SkładkaWysokość != value))
				{
					this._SkładkaWysokość = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SkładkaWysokośćEURO", DbType = "VarChar(512) NOT NULL", CanBeNull = false)]
        public string SkładkaWysokośćEURO
        {
            get
            {
                return this._SkładkaWysokośćEURO;
            }
            set
            {
                if ((this._SkładkaWysokośćEURO != value))
                {
                    this._SkładkaWysokośćEURO = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkładkaTermin", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SkładkaTermin
		{
			get
			{
				return this._SkładkaTermin;
			}
			set
			{
				if ((this._SkładkaTermin != value))
				{
					this._SkładkaTermin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkładkaKoszty", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SkładkaKoszty
		{
			get
			{
				return this._SkładkaKoszty;
			}
			set
			{
				if ((this._SkładkaKoszty != value))
				{
					this._SkładkaKoszty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumerRachunku", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string NumerRachunku
		{
			get
			{
				return this._NumerRachunku;
			}
			set
			{
				if ((this._NumerRachunku != value))
				{
					this._NumerRachunku = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NumerRachunkuDE", DbType = "VarChar(512) NOT NULL", CanBeNull = false)]
        public string NumerRachunkuDE
        {
            get
            {
                return this._NumerRachunkuDE;
            }
            set
            {
                if ((this._NumerRachunkuDE != value))
                {
                    this._NumerRachunkuDE = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaBanku", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string NazwaBanku
		{
			get
			{
				return this._NazwaBanku;
			}
			set
			{
				if ((this._NazwaBanku != value))
				{
					this._NazwaBanku = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NazwaBankuDE", DbType = "VarChar(512) NOT NULL", CanBeNull = false)]
        public string NazwaBankuDE
        {
            get
            {
                return this._NazwaBankuDE;
            }
            set
            {
                if ((this._NazwaBankuDE != value))
                {
                    this._NazwaBankuDE = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoDodatkowe", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string InfoDodatkowe
		{
			get
			{
				return this._InfoDodatkowe;
			}
			set
			{
				if ((this._InfoDodatkowe != value))
				{
					this._InfoDodatkowe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PodstawaPrawna", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string PodstawaPrawna
		{
			get
			{
				return this._PodstawaPrawna;
			}
			set
			{
				if ((this._PodstawaPrawna != value))
				{
					this._PodstawaPrawna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Podpis", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Podpis
		{
			get
			{
				return this._Podpis;
			}
			set
			{
				if ((this._Podpis != value))
				{
					this._Podpis = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PodpisDE", DbType = "VarChar(512) NOT NULL", CanBeNull = false)]
        public string PodpisDE
        {
            get
            {
                return this._PodpisDE;
            }
            set
            {
                if ((this._PodpisDE != value))
                {
                    this._PodpisDE = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folder", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Folder
		{
			get
			{
				return this._Folder;
			}
			set
			{
				if ((this._Folder != value))
				{
					this._Folder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typ", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Typ
		{
			get
			{
				return this._Typ;
			}
			set
			{
				if ((this._Typ != value))
				{
					this._Typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNota", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string DataNota
		{
			get
			{
				return this._DataNota;
			}
			set
			{
				if ((this._DataNota != value))
				{
					this._DataNota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchematNumer", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SchematNumer
		{
			get
			{
				return this._SchematNumer;
			}
			set
			{
				if ((this._SchematNumer != value))
				{
					this._SchematNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoDodatkoweDE", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string InfoDodatkoweDE
		{
			get
			{
				return this._InfoDodatkoweDE;
			}
			set
			{
				if ((this._InfoDodatkoweDE != value))
				{
					this._InfoDodatkoweDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PodstawaPrawnaDE", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string PodstawaPrawnaDE
		{
			get
			{
				return this._PodstawaPrawnaDE;
			}
			set
			{
				if ((this._PodstawaPrawnaDE != value))
				{
					this._PodstawaPrawnaDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IloscDni", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string IloscDni
		{
			get
			{
				return this._IloscDni;
			}
			set
			{
				if ((this._IloscDni != value))
				{
					this._IloscDni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaNoty", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string NazwaNoty
		{
			get
			{
				return this._NazwaNoty;
			}
			set
			{
				if ((this._NazwaNoty != value))
				{
					this._NazwaNoty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CkeNumer", DbType="Int NOT NULL")]
		public int CkeNumer
		{
			get
			{
				return this._CkeNumer;
			}
			set
			{
				if ((this._CkeNumer != value))
				{
					this._CkeNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CkeTyp", DbType="SmallInt")]
		public System.Nullable<short> CkeTyp
		{
			get
			{
				return this._CkeTyp;
			}
			set
			{
				if ((this._CkeTyp != value))
				{
					this._CkeTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CkeLp", DbType="SmallInt NOT NULL")]
		public short CkeLp
		{
			get
			{
				return this._CkeLp;
			}
			set
			{
				if ((this._CkeLp != value))
				{
					this._CkeLp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeIdent", DbType="VarChar(8)")]
		public string OpeIdent
		{
			get
			{
				return this._OpeIdent;
			}
			set
			{
				if ((this._OpeIdent != value))
				{
					this._OpeIdent = value;
				}
			}
		}
	}
	
	public partial class T2S_GetReportsGenNotResult
	{
		
		private string _ReportName;
		
		private System.Nullable<int> _Zrodlo;
		
		private System.Nullable<int> _Wydruk;
		
		private System.Nullable<int> _Format;
		
		public T2S_GetReportsGenNotResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="NVarChar(100)")]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this._ReportName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zrodlo", DbType="Int")]
		public System.Nullable<int> Zrodlo
		{
			get
			{
				return this._Zrodlo;
			}
			set
			{
				if ((this._Zrodlo != value))
				{
					this._Zrodlo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wydruk", DbType="Int")]
		public System.Nullable<int> Wydruk
		{
			get
			{
				return this._Wydruk;
			}
			set
			{
				if ((this._Wydruk != value))
				{
					this._Wydruk = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Format", DbType="Int")]
		public System.Nullable<int> Format
		{
			get
			{
				return this._Format;
			}
			set
			{
				if ((this._Format != value))
				{
					this._Format = value;
				}
			}
		}
	}
	
	public partial class T2S_GetEmailNotaStatutResult
	{
		
		private string _Ope_ident;
		
		private string _Email;
		
		public T2S_GetEmailNotaStatutResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ident", DbType="VarChar(8)")]
		public string Ope_ident
		{
			get
			{
				return this._Ope_ident;
			}
			set
			{
				if ((this._Ope_ident != value))
				{
					this._Ope_ident = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(512)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class T2S_Procedure_CounterGenerateNotsResult
	{
		
		private System.Nullable<System.DateTime> _Column1;
		
		public T2S_Procedure_CounterGenerateNotsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENotaResult
	{
		
		private System.Nullable<int> _CEK_KntNumer;
		
		private System.Nullable<int> _CEK_ID;
		
		private string _FiltrSQL;
		
		private string _SchematNumer;
		
		private string _Knt_Akronim;
		
		private System.Nullable<short> _Knt_GIDTyp;
		
		private int _Knt_GIDNumer;
		
		private string _Email;
		
		private string _Message_EMail;
		
		public T2S_Procedure_GenNagEtapKnt_Uzupelniona_ENotaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_KntNumer", DbType="Int")]
		public System.Nullable<int> CEK_KntNumer
		{
			get
			{
				return this._CEK_KntNumer;
			}
			set
			{
				if ((this._CEK_KntNumer != value))
				{
					this._CEK_KntNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_ID", DbType="Int")]
		public System.Nullable<int> CEK_ID
		{
			get
			{
				return this._CEK_ID;
			}
			set
			{
				if ((this._CEK_ID != value))
				{
					this._CEK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiltrSQL", DbType="NVarChar(107)")]
		public string FiltrSQL
		{
			get
			{
				return this._FiltrSQL;
			}
			set
			{
				if ((this._FiltrSQL != value))
				{
					this._FiltrSQL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchematNumer", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SchematNumer
		{
			get
			{
				return this._SchematNumer;
			}
			set
			{
				if ((this._SchematNumer != value))
				{
					this._SchematNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_Akronim", DbType="VarChar(20)")]
		public string Knt_Akronim
		{
			get
			{
				return this._Knt_Akronim;
			}
			set
			{
				if ((this._Knt_Akronim != value))
				{
					this._Knt_Akronim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDTyp", DbType="SmallInt")]
		public System.Nullable<short> Knt_GIDTyp
		{
			get
			{
				return this._Knt_GIDTyp;
			}
			set
			{
				if ((this._Knt_GIDTyp != value))
				{
					this._Knt_GIDTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDNumer", DbType="Int NOT NULL")]
		public int Knt_GIDNumer
		{
			get
			{
				return this._Knt_GIDNumer;
			}
			set
			{
				if ((this._Knt_GIDNumer != value))
				{
					this._Knt_GIDNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_EMail", DbType="VarChar(1321)")]
		public string Message_EMail
		{
			get
			{
				return this._Message_EMail;
			}
			set
			{
				if ((this._Message_EMail != value))
				{
					this._Message_EMail = value;
				}
			}
		}
	}
	
	public partial class T2S_GenNagEtapKntResult
	{
		
		private System.Nullable<int> _CEK_KntNumer;
		
		private System.Nullable<int> _CEK_ID;
		
		private string _FiltrSQL;
		
		private string _SchematNumer;
		
		private string _Knt_Akronim;
		
		private System.Nullable<short> _Knt_GIDTyp;
		
		private int _Knt_GIDNumer;
		
		private string _Email;
		
		private string _Subject_Email;
		
		private string _Message_EMail;
		
		public T2S_GenNagEtapKntResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_KntNumer", DbType="Int")]
		public System.Nullable<int> CEK_KntNumer
		{
			get
			{
				return this._CEK_KntNumer;
			}
			set
			{
				if ((this._CEK_KntNumer != value))
				{
					this._CEK_KntNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_ID", DbType="Int")]
		public System.Nullable<int> CEK_ID
		{
			get
			{
				return this._CEK_ID;
			}
			set
			{
				if ((this._CEK_ID != value))
				{
					this._CEK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiltrSQL", DbType="NVarChar(107)")]
		public string FiltrSQL
		{
			get
			{
				return this._FiltrSQL;
			}
			set
			{
				if ((this._FiltrSQL != value))
				{
					this._FiltrSQL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchematNumer", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SchematNumer
		{
			get
			{
				return this._SchematNumer;
			}
			set
			{
				if ((this._SchematNumer != value))
				{
					this._SchematNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_Akronim", DbType="VarChar(20)")]
		public string Knt_Akronim
		{
			get
			{
				return this._Knt_Akronim;
			}
			set
			{
				if ((this._Knt_Akronim != value))
				{
					this._Knt_Akronim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDTyp", DbType="SmallInt")]
		public System.Nullable<short> Knt_GIDTyp
		{
			get
			{
				return this._Knt_GIDTyp;
			}
			set
			{
				if ((this._Knt_GIDTyp != value))
				{
					this._Knt_GIDTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDNumer", DbType="Int NOT NULL")]
		public int Knt_GIDNumer
		{
			get
			{
				return this._Knt_GIDNumer;
			}
			set
			{
				if ((this._Knt_GIDNumer != value))
				{
					this._Knt_GIDNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_Email", DbType="VarChar(124) NOT NULL", CanBeNull=false)]
		public string Subject_Email
		{
			get
			{
				return this._Subject_Email;
			}
			set
			{
				if ((this._Subject_Email != value))
				{
					this._Subject_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_EMail", DbType="VarChar(1237)")]
		public string Message_EMail
		{
			get
			{
				return this._Message_EMail;
			}
			set
			{
				if ((this._Message_EMail != value))
				{
					this._Message_EMail = value;
				}
			}
		}
	}
	
	public partial class T2S_GenNagEtapKntTAKResult
	{
		
		private System.Nullable<int> _CEK_KntNumer;
		
		private System.Nullable<int> _CEK_ID;
		
		private string _FiltrSQL;
		
		private string _SchematNumer;
		
		private string _Knt_Akronim;
		
		private System.Nullable<short> _Knt_GIDTyp;
		
		private int _Knt_GIDNumer;
		
		private string _Email;
		
		private string _Subject_Email;
		
		private string _Message_EMail;
		
		public T2S_GenNagEtapKntTAKResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_KntNumer", DbType="Int")]
		public System.Nullable<int> CEK_KntNumer
		{
			get
			{
				return this._CEK_KntNumer;
			}
			set
			{
				if ((this._CEK_KntNumer != value))
				{
					this._CEK_KntNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_ID", DbType="Int")]
		public System.Nullable<int> CEK_ID
		{
			get
			{
				return this._CEK_ID;
			}
			set
			{
				if ((this._CEK_ID != value))
				{
					this._CEK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiltrSQL", DbType="NVarChar(107)")]
		public string FiltrSQL
		{
			get
			{
				return this._FiltrSQL;
			}
			set
			{
				if ((this._FiltrSQL != value))
				{
					this._FiltrSQL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchematNumer", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SchematNumer
		{
			get
			{
				return this._SchematNumer;
			}
			set
			{
				if ((this._SchematNumer != value))
				{
					this._SchematNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_Akronim", DbType="VarChar(20)")]
		public string Knt_Akronim
		{
			get
			{
				return this._Knt_Akronim;
			}
			set
			{
				if ((this._Knt_Akronim != value))
				{
					this._Knt_Akronim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDTyp", DbType="SmallInt")]
		public System.Nullable<short> Knt_GIDTyp
		{
			get
			{
				return this._Knt_GIDTyp;
			}
			set
			{
				if ((this._Knt_GIDTyp != value))
				{
					this._Knt_GIDTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDNumer", DbType="Int NOT NULL")]
		public int Knt_GIDNumer
		{
			get
			{
				return this._Knt_GIDNumer;
			}
			set
			{
				if ((this._Knt_GIDNumer != value))
				{
					this._Knt_GIDNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_Email", DbType="VarChar(117) NOT NULL", CanBeNull=false)]
		public string Subject_Email
		{
			get
			{
				return this._Subject_Email;
			}
			set
			{
				if ((this._Subject_Email != value))
				{
					this._Subject_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_EMail", DbType="VarChar(1237)")]
		public string Message_EMail
		{
			get
			{
				return this._Message_EMail;
			}
			set
			{
				if ((this._Message_EMail != value))
				{
					this._Message_EMail = value;
				}
			}
		}
	}
	
	public partial class T2S_GenNagEtapKntNIEResult
	{
		
		private System.Nullable<int> _CEK_KntNumer;
		
		private System.Nullable<int> _CEK_ID;
		
		private string _FiltrSQL;
		
		private string _SchematNumer;
		
		private string _Knt_Akronim;
		
		private System.Nullable<short> _Knt_GIDTyp;
		
		private int _Knt_GIDNumer;
		
		private string _Email;
		
		private string _Subject_Email;
		
		private string _Message_EMail;
		
		public T2S_GenNagEtapKntNIEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_KntNumer", DbType="Int")]
		public System.Nullable<int> CEK_KntNumer
		{
			get
			{
				return this._CEK_KntNumer;
			}
			set
			{
				if ((this._CEK_KntNumer != value))
				{
					this._CEK_KntNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEK_ID", DbType="Int")]
		public System.Nullable<int> CEK_ID
		{
			get
			{
				return this._CEK_ID;
			}
			set
			{
				if ((this._CEK_ID != value))
				{
					this._CEK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiltrSQL", DbType="NVarChar(107)")]
		public string FiltrSQL
		{
			get
			{
				return this._FiltrSQL;
			}
			set
			{
				if ((this._FiltrSQL != value))
				{
					this._FiltrSQL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchematNumer", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string SchematNumer
		{
			get
			{
				return this._SchematNumer;
			}
			set
			{
				if ((this._SchematNumer != value))
				{
					this._SchematNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_Akronim", DbType="VarChar(20)")]
		public string Knt_Akronim
		{
			get
			{
				return this._Knt_Akronim;
			}
			set
			{
				if ((this._Knt_Akronim != value))
				{
					this._Knt_Akronim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDTyp", DbType="SmallInt")]
		public System.Nullable<short> Knt_GIDTyp
		{
			get
			{
				return this._Knt_GIDTyp;
			}
			set
			{
				if ((this._Knt_GIDTyp != value))
				{
					this._Knt_GIDTyp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_GIDNumer", DbType="Int NOT NULL")]
		public int Knt_GIDNumer
		{
			get
			{
				return this._Knt_GIDNumer;
			}
			set
			{
				if ((this._Knt_GIDNumer != value))
				{
					this._Knt_GIDNumer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject_Email", DbType="VarChar(117) NOT NULL", CanBeNull=false)]
		public string Subject_Email
		{
			get
			{
				return this._Subject_Email;
			}
			set
			{
				if ((this._Subject_Email != value))
				{
					this._Subject_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message_EMail", DbType="VarChar(1237)")]
		public string Message_EMail
		{
			get
			{
				return this._Message_EMail;
			}
			set
			{
				if ((this._Message_EMail != value))
				{
					this._Message_EMail = value;
				}
			}
		}
	}
	
	public partial class T2S_Procedure_PobierzAdresMailowyResult
	{
		
		private string _Knt_Email;
		
		public T2S_Procedure_PobierzAdresMailowyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Knt_Email", DbType="VarChar(255)")]
		public string Knt_Email
		{
			get
			{
				return this._Knt_Email;
			}
			set
			{
				if ((this._Knt_Email != value))
				{
					this._Knt_Email = value;
				}
			}
		}
	}
	
	public partial class T2S_Procedure_PobierzAdresMailowyOdbiorcyResult
	{
		
		private string _atr_wartosc;
		
		public T2S_Procedure_PobierzAdresMailowyOdbiorcyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atr_wartosc", DbType="VarChar(512)")]
		public string atr_wartosc
		{
			get
			{
				return this._atr_wartosc;
			}
			set
			{
				if ((this._atr_wartosc != value))
				{
					this._atr_wartosc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
